from __future__ import annotations

from app.services.tools.toolboxes import get_official_toolbox


DEFAULT_AGENTS = [
    {
        "name": "Master Agent",
        "type": "master",
        "provider": "ark",
        "avatar_color": "#1677ff",
        "description": "负责需求研判、任务拆解、调度与成果聚合。",
        "system_prompt": "你是 AgentHub Master Agent，负责需求拆解、权限判断、调度 Worker、聚合 Reviewer 结论和最终交付；内部调度信息不要直接暴露给用户。",
        "tools": get_official_toolbox("master"),
        "capabilities": [
            {"label": "调度", "category": "编排", "proficiency": 5},
            {"label": "拆解", "category": "编排", "proficiency": 5},
            {"label": "聚合", "category": "编排", "proficiency": 4},
            {"label": "审查", "category": "质量", "proficiency": 4},
        ],
    },
    {
        "name": "Frontend Worker",
        "type": "frontend",
        "provider": "ark",
        "avatar_color": "#059669",
        "description": "React、TypeScript、Ant Design 与交互实现专家。",
        "system_prompt": "你是 Frontend Worker，使用授权工具完成前端实现、Web 产物生成、浏览器预览和交互验收，输出可验证的修改摘要。",
        "tools": get_official_toolbox("frontend"),
        "capabilities": [
            {"label": "前端", "category": "编码", "proficiency": 5},
            {"label": "React", "category": "编码", "proficiency": 5},
            {"label": "UI", "category": "设计", "proficiency": 4},
        ],
    },
    {
        "name": "Backend Worker",
        "type": "backend",
        "provider": "ark",
        "avatar_color": "#7C3AED",
        "description": "FastAPI、SQLAlchemy、PostgreSQL 与实时服务专家。",
        "system_prompt": "你是 Backend Worker，负责 API、数据库、任务队列、实时事件和测试验证，优先使用授权工具检查并返回可落地结果。",
        "tools": get_official_toolbox("backend"),
        "capabilities": [
            {"label": "后端", "category": "编码", "proficiency": 5},
            {"label": "API", "category": "架构", "proficiency": 5},
            {"label": "数据库", "category": "架构", "proficiency": 4},
        ],
    },
    {
        "name": "Reviewer",
        "type": "reviewer",
        "provider": "ark",
        "avatar_color": "#f59e0b",
        "description": "审查产物完整性、一致性、风险和演示可用性。",
        "system_prompt": "你是 Reviewer，负责产物 Diff、测试运行、安全审计和文档审查，只输出审查结论、风险和修复建议。",
        "tools": get_official_toolbox("reviewer"),
        "capabilities": [
            {"label": "审查", "category": "质量", "proficiency": 5},
            {"label": "质量", "category": "质量", "proficiency": 5},
            {"label": "测试", "category": "测试", "proficiency": 4},
        ],
    },
    {
        "name": "Deploy Agent",
        "type": "deploy",
        "provider": "ark",
        "avatar_color": "#dc2626",
        "description": "负责预览链接、静态发布、容器部署和打包。",
        "system_prompt": "你是 Deploy Agent，负责产物导出、预览部署、回滚和发布记录，执行前说明风险并输出部署状态。",
        "tools": get_official_toolbox("deploy"),
        "capabilities": [
            {"label": "部署", "category": "运维", "proficiency": 5},
            {"label": "预览", "category": "运维", "proficiency": 4},
            {"label": "运维", "category": "运维", "proficiency": 4},
        ],
    },
    {
        "name": "Writing Agent",
        "type": "writing",
        "provider": "ark",
        "avatar_color": "#2563eb",
        "description": "负责方案、报告、标书、答辩稿、PDF/Word/PPT 产物写作与修订。",
        "system_prompt": "你是 Writing Agent，面向正式交付写作，能够读取附件、生成结构化正文，并调用 artifact 工具生成 PDF、Word 或 PPT 产物。",
        "tools": get_official_toolbox("writing"),
        "capabilities": [
            {"label": "写作", "category": "文档", "proficiency": 5},
            {"label": "PDF", "category": "产物", "proficiency": 4},
            {"label": "PPT", "category": "产物", "proficiency": 4},
            {"label": "审稿", "category": "质量", "proficiency": 4},
        ],
    },
    {
        "name": "Daily Chat Agent",
        "type": "chat",
        "provider": "ark",
        "avatar_color": "#14b8a6",
        "description": "负责日常问答、轻量咨询、附件摘要和上下文续聊。",
        "system_prompt": "你是 Daily Chat Agent，负责自然、简洁、可靠的日常对话；遇到文件时先摘要再回答，避免暴露内部推理。",
        "tools": get_official_toolbox("chat"),
        "capabilities": [
            {"label": "聊天", "category": "通用", "proficiency": 5},
            {"label": "问答", "category": "通用", "proficiency": 5},
            {"label": "附件摘要", "category": "文件", "proficiency": 4},
        ],
    },
]

DEFAULT_SKILLS = [
    {
        "name": "需求分析 Skill",
        "description": "把模糊输入压缩成目标、约束、风险和下一步动作，供主控 Agent 快速决策。",
        "category": "analysis",
        "source": "system",
        "content": "分析用户目标，提取关键约束、可执行动作、风险和需要追问的信息。输出简洁结构化结论。",
        "prompt": "你是 AgentHub 内置需求分析 Skill。只返回可用于执行决策的简短分析，不暴露内部推理。",
        "tags": ["analysis", "planning", "agentic-loop"],
        "tools": [],
    },
    {
        "name": "产物审查 Skill",
        "description": "检查生成内容是否符合用户目标、演示可用性、风险和遗漏。",
        "category": "review",
        "source": "system",
        "content": "审查产物完整性、可演示性和风险，给出通过/需修改结论。",
        "prompt": "你是 AgentHub 内置审查 Skill。用简短语言列出关键审查结论和必要修复建议。",
        "tags": ["review", "qa", "artifact"],
        "tools": [],
    },
]

DEFAULT_PERMISSIONS = [
    "session:create",
    "session:read",
    "session:delete",
    "session:export",
    "agent:use",
    "agent:create",
    "agent:update",
    "agent:delete",
    "agent:publish",
    "agent:debug",
    "workspace:create",
    "workspace:read",
    "project:manage",
    "knowledge:manage",
    "file:upload",
    "file:read",
    "file:write",
    "artifact:create",
    "artifact:read",
    "artifact:update",
    "artifact:export",
    "tool:create",
    "tool:update",
    "tool:invoke",
    "sandbox:run",
    "browser:preview",
    "db:inspect",
    "api:test",
    "test:run",
    "security:audit",
    "document:review",
    "deploy:preview",
    "deploy:rollback",
    "workflow:manage",
    "mcp:invoke",
    "security:view",
    "security:manage",
    "log:view:own",
    "log:view:all",
    "user:manage",
    "config:manage",
]

DEFAULT_ROLE_MAP = {
    "ROLE_USER": ["session:create", "session:read", "session:delete", "session:export", "agent:use", "workspace:create", "workspace:read", "project:manage", "knowledge:manage", "file:upload", "file:read", "artifact:create", "artifact:read", "artifact:export", "workflow:manage", "mcp:invoke", "tool:invoke", "security:view", "log:view:own"],
    "ROLE_AGENT_PROVIDER": ["agent:create", "agent:update", "agent:delete", "agent:publish", "tool:create", "tool:update"],
    "ROLE_DEVELOPER": ["agent:debug", "file:write", "sandbox:run", "db:inspect", "api:test", "test:run", "log:view:all"],
    "ROLE_ADMIN": ["user:manage", "security:manage", "config:manage", "log:view:all", "agent:publish"],
}
